# Learning and Testing SEG-Y with `segyio` Python Package

In [1]:
import segyio
import numpy as np

In [2]:
segy_file = '/Users/ajelenak/Downloads/PoroTomo_iDAS16043_160311200818.sgy'

In [3]:
f = segyio.open(segy_file, mode='r', strict=False)

## Basic Properties

In [4]:
print(f.format)

4-byte IEEE float


In [5]:
f.text[0]

bytearray(b'C01 Client: Uni. Wisconsin                                                      C02 Field: PoroTomo                                                             C03 Fibre: Trenched Surface Fibre                                               C04 Data collected by Silixa iDAS, Distributed Fibre Optic Sensor               C05 iDAS S/N: iDAS16043                                                         C06 SEGY Format: Rev.1, IEEE 32bit float, big endian                            C07 Field Recording Filename: BNL_IDAS__160311200818.tdms                       C08 Continuous acquisition data converted to SEGY                               C09 UTC Timestamp of first sample: 11-Mar-2016 20:08:18.862432014               C10                                                                             C11                                                                             C12                                                                             C13 Receiver positions are i

In [6]:
f.attributes(segyio.TraceField.SourceX)[:]

array([0, 0, 0, ..., 0, 0, 0], dtype=int32)

In [7]:
f.tracecount

8721

In [8]:
f.samples

array([0.0000e+00, 1.0000e+00, 2.0000e+00, ..., 2.9997e+04, 2.9998e+04,
       2.9999e+04])

In [9]:
f.trace

Trace(traces = 8721, samples = 30000)

In [10]:
f.trace[15]

array([ 0.02657334,  0.09238194,  0.10524189, ...,  0.00121248,
       -0.0014092 , -0.00045777], dtype=float32)

In [11]:
print(f.offsets)

None


In [12]:
print(f.sorting)

None


In [13]:
print("Available offsets and their corresponding byte value:")
for x in segyio.TraceField.enums():
    print("  {}: {}".format(str(x), x))

Available offsets and their corresponding byte value:
  TRACE_SEQUENCE_LINE: TRACE_SEQUENCE_LINE
  TRACE_SEQUENCE_FILE: TRACE_SEQUENCE_FILE
  FieldRecord: FieldRecord
  TraceNumber: TraceNumber
  EnergySourcePoint: EnergySourcePoint
  CDP: CDP
  CDP_TRACE: CDP_TRACE
  TraceIdentificationCode: TraceIdentificationCode
  NSummedTraces: NSummedTraces
  NStackedTraces: NStackedTraces
  DataUse: DataUse
  offset: offset
  ReceiverGroupElevation: ReceiverGroupElevation
  SourceSurfaceElevation: SourceSurfaceElevation
  SourceDepth: SourceDepth
  ReceiverDatumElevation: ReceiverDatumElevation
  SourceDatumElevation: SourceDatumElevation
  SourceWaterDepth: SourceWaterDepth
  GroupWaterDepth: GroupWaterDepth
  ElevationScalar: ElevationScalar
  SourceGroupScalar: SourceGroupScalar
  SourceX: SourceX
  SourceY: SourceY
  GroupX: GroupX
  GroupY: GroupY
  CoordinateUnits: CoordinateUnits
  WeatheringVelocity: WeatheringVelocity
  SubWeatheringVelocity: SubWeatheringVelocity
  SourceUpholeTime: So

In [14]:
segyio.tools.dt(f)

1000.0

In [15]:
meta = segyio.tools.metadata(f)

In [16]:
meta.tracecount

8721

In [17]:
print(meta.format)

4-byte IEEE float


In [18]:
meta.ext_headers

0

In [19]:
meta.iline

189

In [20]:
meta.xline

193

In [21]:
meta.samples

array([0.0000e+00, 1.0000e+00, 2.0000e+00, ..., 2.9997e+04, 2.9998e+04,
       2.9999e+04])

In [22]:
meta.samples.shape

(30000,)

In [23]:
print(meta.sorting)

None


In [24]:
print(meta.xlines)

None
